# Write your MySQL query statement below
-- SELECT DISTINCT SALARY AS SecondHighestSalary FROM EMPLOYEE
-- ORDER BY SALARY DESC
-- LIMIT 1 OFFSET 1;

-- SELECT MAX(SALARY) AS SecondHighestSalary 
-- FROM EMPLOYEE
-- WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT IFNULL(
    (
        SELECT DISTINCT MAX(SALARY) FROM EMPLOYEE WHERE 
        SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)
    ),  NULL
) AS SecondHighestSalary;


-- SELECT IFNULL(
--     (SELECT DISTINCT SALARY
--     FROM EMPLOYEE
--     ORDER BY SALARY DESC
--     LIMIT 1 OFFSET 1), NULL
-- )AS SecondHighestSalary;